# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170910_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_slug',
        ),
    ]
